# Generated by Django 4.2.2 on 2024-04-17 09:33

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(error_messages='Nickname must be at least 2 chars long!', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=30, validators=[users.models.first_letter_validator])),
                ('last_name', models.CharField(max_length=30, validators=[users.models.first_letter_validator])),
                ('chef', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
