# Generated by Django 4.2.2 on 2024-05-28 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(error_messages={'min_length': 'Nickname must be at least 2 chars long!'}, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
