# Generated by Django 4.2.2 on 2024-05-31 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_author'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipe',
            table='recipes_recipe',
        ),
    ]
